# mysql setting
mysql:
  database: chatbot
  user: root
  #host: mysql-service
  host: localhost
  password: glossa_address_parse
  port: 3306
  max_connections: 100

# redis 配置
redis:
  #host: redis-service
  host: localhost
  password: 123456
  port: 3306
  db: 0

# chabot 设置
chatbot:
  TRAIN_DATA_PATH: /chatbot/
  MODEL_PATH: models/
